### ISSUE TITLE
Requesting for entire finetune.ipynb

### ISSUE THREAD

**Issue by chakka-guna-sekhar-venkata-chennaiah** [nachiketashunya/AMLChallenge#1]
Since I understand that dataprep.py creates a file and that will be used for the fine tuning right. But when I opened fine-tuning ipynb file i just see the three to four code blocks and also i didn't see of using that generated file for the fine tuning. So please share the entire ipynb file for better understanding of the approach.  Congratulations for being the winners 🥳 🏆. 

Thanks 
Guna Sekhar

**Comment by kushal150699** [comment]
When you will run the Code blocks , llama Factory WebUI will open , then there you have to provide the data directory path.

**Comment by nachiketashunya** [comment]
No further questions.
